name: CommandPoints
main: pgDev.bukkit.CommandPoints.CommandPoints
version: 0.1
author: Devil Boy
description: A command-based merit system.

permissions:
    CommandPoints.*:
        default: op
        description: Gives access to all CommandPoints commands.
        children:
            scs.create: true
            scs.use: true
    CommandPoints.setPoints:
        default: op
        description: Can give/remove points from players.
    CommandPoints.checkPoints:
        default: op
        description: Can check another user's points.